### ISSUE TITLE
Crash upon loading game, reverting to 1.6.3 fixes

### ISSUE THREAD

**Issue by AvangionQ** [JohnnyBazooka89/StSModTheBlackbeard#8]
Exception in thread "LWJGL Application" com.badlogic.gdx.utils.GdxRuntimeException: java.lang.NoSuchMethodError: basemod.BaseMod.addKeyword(Ljava/lang/String;Ljava/lang/String;[Ljava/lang/String;Ljava/lang/String;)V
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:133)
Caused by: java.lang.NoSuchMethodError: basemod.BaseMod.addKeyword(Ljava/lang/String;Ljava/lang/String;[Ljava/lang/String;Ljava/lang/String;)V
	at blackbeard.TheBlackbeardMod.lambda$loadCustomKeywordsForLanguage$0(TheBlackbeardMod.java:363)
	at java.util.Map.forEach(Map.java:630)
	at blackbeard.TheBlackbeardMod.loadCustomKeywordsForLanguage(TheBlackbeardMod.java:361)
	at blackbeard.TheBlackbeardMod.receiveEditKeywords(TheBlackbeardMod.java:335)
	at basemod.BaseMod.publishEditKeywords(BaseMod.java:2337)
	at basemod.patches.com.megacrit.cardcrawl.helpers.GameDictionary.PostKeywordInitialize.Postfix(PostKeywordInitialize.java:10)
	at com.megacrit.cardcrawl.helpers.GameDictionary.initialize(GameDictionary.java:96)
	at com.megacrit.cardcrawl.core.CardCrawlGame.create(CardCrawlGame.java:265)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:149)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)

**Comment by JohnnyBazooka89** [comment]
The newest version of my mod requires newer version of BaseMod and ModTheSpire. The only thing i can do is changing the minimum version of ModTheSpire in requirements, but I see little point of that, because most people play my mod on Steam Workshop, and neither BaseMod nor ModTheSpire are updated on Github anymore.
